# Generated by Django 4.0.2 on 2022-05-31 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='places',
            options={'ordering': ['-creates_at', 'title'], 'verbose_name': 'Место', 'verbose_name_plural': 'Места'},
        ),
    ]
